Empezamos armando el dataframe con el que vamos a trabajar:

In [79]:
import pandas as pd

# Leer el archivo csv original especificando el delimitador como ';'
df_original = pd.read_csv("Calidad_de_agua_2021.csv", sep=';')

# Creamos una copia del DataFrame
df = df_original.copy()

# Añadimos un dataframe que creamos con la distancia aproximada de donde se tomaron las muestras
df_distancias = pd.read_csv("distancias.csv");
df_con_id = pd.read_csv("DataFrame_con_identificadores_completados.csv")

In [80]:
#Mostramos el df para ver si cargo bien
#df
#df_distancias

In [81]:
#Esto es para que nos muestre todas las columnas y las filas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [82]:
# Le hacemos un info para indentificar los tipos

#df.info(verbose=True)

Empezamos a ver los tipos y modificarlos para que sean datos mas manejables

In [83]:
#df['espumas'].value_counts(dropna=False)

In [84]:
# Aca identificamos las que estan escritas dif (para saber sus diferencias tambien)
#for idx in df["espumas"].value_counts().items():
#    print(idx)

In [85]:
# Remplazo los valores q estan escritos distintos para q esten iguales
df['espumas'] = df['espumas'].replace("Ausencia ", 'Ausencia')
df['espumas'] = df['espumas'].replace("no se midió", pd.NA)

In [86]:
# Aca miramos la cantidad de NaN y miramos cuales los los tipos que contiene
#print(df["espumas"].isna().sum())
#print(df["espumas"].unique())

In [87]:
#Los pasamos a Booleano para mejor manupilacion  y los nulos los ignoramos para que sigan estando
df['espumas'] = df['espumas'].map({'Presencia': True, 'Ausencia': False}, na_action= 'ignore')

In [88]:
#Verificamos que efectivamente no se borraron los NaN
#df["espumas"].isna().sum()

In [89]:
#Empezamos a curar otra columna, este caso "fecha"
#df['fecha'].value_counts(dropna=False)

In [90]:
#pasamos la fecha a formato date
df['fecha'] = pd.to_datetime(df['fecha'], format='%d/%m/%Y')

In [91]:
# Miramos el contenido de campaña 
#df['campaña'].value_counts()

In [92]:
# Miramos el contenido de la temperatura del agua 
#df['tem_agua'].value_counts(dropna=False)

In [93]:
# Reemplazas a los "no se midio" por NaN y dsp lo pasa a tipo numerico, en este caso uso el ignore porque quiero 
# asegurarme que unicamente los "no se midio" se esten cambiando
df['tem_agua'] = df['tem_agua'].replace("no se midió", pd.NA)
df['tem_agua'] = pd.to_numeric(df['tem_agua'] )# , errors='ignore')

In [94]:
# Hacemos lo mismo con los datos del aire 
df['tem_aire'] = df['tem_aire'].replace("no se midió", pd.NA)
df['tem_aire'] = pd.to_numeric(df['tem_aire']) #, errors='ignore')

In [95]:
# Miramos que datos tienen 
#df['ica'].value_counts(dropna=False)

In [96]:
#  Cambiamos los no se midio por NaN y pasamos los datos a tipo numerico (los que pueden)


df['od'] = df['od'].replace("no se midió", pd.NA)
df['od'] = pd.to_numeric(df['od'], errors='ignore')

df['ph'] = df['ph'].replace("no se midió", pd.NA)
df['ph'] = pd.to_numeric(df['ph'], errors='ignore')

df['colif_fecales_ufc_100ml'] = df['colif_fecales_ufc_100ml'].replace("no se midió", pd.NA) 
df['colif_fecales_ufc_100ml'] = pd.to_numeric(df['colif_fecales_ufc_100ml'], errors='ignore')

df['escher_coli_ufc_100ml'] = df['escher_coli_ufc_100ml'].replace("no se midió", pd.NA)
df['escher_coli_ufc_100ml'] = pd.to_numeric(df['escher_coli_ufc_100ml'], errors='ignore')

df['enteroc_ufc_100ml'] = df['enteroc_ufc_100ml'].replace("no se midió", pd.NA)
df['enteroc_ufc_100ml'] = pd.to_numeric(df['enteroc_ufc_100ml'], errors='ignore')

df['nitrato_mg_l'] = df['nitrato_mg_l'].replace("no se midió", pd.NA)
df['nitrato_mg_l'] = pd.to_numeric(df['nitrato_mg_l'], errors='ignore')

df['nh4_mg_l'] = df['nh4_mg_l'].replace("no se midió", pd.NA)
df['nh4_mg_l'] = pd.to_numeric(df['nh4_mg_l'], errors='ignore')

df['p_total_l_mg_l'] = df['p_total_l_mg_l'].replace("no se midió", pd.NA)
df['p_total_l_mg_l'] = pd.to_numeric(df['p_total_l_mg_l'], errors='ignore')

df['fosf_ortofos_mg_l'] = df['fosf_ortofos_mg_l'].replace("no se midió", pd.NA)
df['fosf_ortofos_mg_l'] = pd.to_numeric(df['fosf_ortofos_mg_l'], errors='ignore')

df['dbo_mg_l'] = df['dbo_mg_l'].replace("no se midió", pd.NA)
df['dbo_mg_l'] = pd.to_numeric(df['dbo_mg_l'], errors='ignore')

df['dqo_mg_l'] = df['dqo_mg_l'].replace("no se midió", pd.NA)
df['dqo_mg_l'] = pd.to_numeric(df['dqo_mg_l'], errors='ignore')

df['turbiedad_ntu'] = df['turbiedad_ntu'].replace("no se midió", pd.NA)
df['turbiedad_ntu'] = pd.to_numeric(df['turbiedad_ntu'], errors='ignore')

df['hidr_deriv_petr_ug_l'] = df['hidr_deriv_petr_ug_l'].replace("no se midió", pd.NA)
df['hidr_deriv_petr_ug_l'] = pd.to_numeric(df['hidr_deriv_petr_ug_l'], errors='ignore')

df['cr_total_mg_l'] = df['cr_total_mg_l'].replace("no se midió", pd.NA)
df['cr_total_mg_l'] = pd.to_numeric(df['cr_total_mg_l'], errors='ignore')

df['cd_total_mg_l'] = df['cd_total_mg_l'].replace("no se midió", pd.NA)
df['cd_total_mg_l'] = pd.to_numeric(df['cd_total_mg_l'], errors='ignore')

df['clorofila_a_ug_l'] = df['clorofila_a_ug_l'].replace("no se midió", pd.NA)
df['clorofila_a_ug_l'] = pd.to_numeric(df['clorofila_a_ug_l'], errors='ignore')

df['microcistina_ug_l'] = df['microcistina_ug_l'].replace("no se midió", pd.NA)
df['microcistina_ug_l'] = pd.to_numeric(df['microcistina_ug_l'], errors='ignore')

df['ica'] = df['ica'].replace("no se midió", pd.NA)
df['ica'] = pd.to_numeric(df['ica'], errors='ignore')

C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['od'] = pd.to_numeric(df['od'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:8: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['ph'] = pd.to_numeric(df['ph'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:11: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['colif_fecales_ufc_100ml'] = pd.to_numeric(df['colif_fecales_ufc_100ml'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:14: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['escher_coli_ufc_100ml'] = pd.to_numeric(df['escher_coli_ufc_100ml'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:17: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['enteroc_ufc_100ml'] = pd.to_numeric(df['enteroc_ufc_100ml'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:20: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['nitrato_mg_l'] = pd.to_numeric(df['nitrato_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:23: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['nh4_mg_l'] = pd.to_numeric(df['nh4_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['p_total_l_mg_l'] = pd.to_numeric(df['p_total_l_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:29: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['fosf_ortofos_mg_l'] = pd.to_numeric(df['fosf_ortofos_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:32: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['dbo_mg_l'] = pd.to_numeric(df['dbo_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:35: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['dqo_mg_l'] = pd.to_numeric(df['dqo_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:38: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['turbiedad_ntu'] = pd.to_numeric(df['turbiedad_ntu'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['hidr_deriv_petr_ug_l'] = pd.to_numeric(df['hidr_deriv_petr_ug_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:44: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['cr_total_mg_l'] = pd.to_numeric(df['cr_total_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:47: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['cd_total_mg_l'] = pd.to_numeric(df['cd_total_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:50: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['clorofila_a_ug_l'] = pd.to_numeric(df['clorofila_a_ug_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:53: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['microcistina_ug_l'] = pd.to_numeric(df['microcistina_ug_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3807158427.py:56: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['ica'] = pd.to_numeric(df['ica'], errors='ignore')

In [97]:
# Corroboramos como van quedando los datos
#df.info()

In [98]:
#Los pasamos a Booleano los que quedaban con (Presencia, Ausencia y "no se midio"), de la misma manera que hicimos con la columna Espuma

# Aca identificamos las la dif entre como estan escritos
#for idx in df['olores'].value_counts().items():
#    print(idx)

In [99]:
# Remplazo los valores q estan escritos distintos para q esten iguales
df['olores'] = df['olores'].replace("Ausencia ", 'Ausencia')
df['olores'] = df['olores'].replace("no se midió", pd.NA)

#Los pasamos a Booleano para mejor manupilacion 
df['olores'] = df['olores'].map({'Presencia': True, 'Ausencia': False})

In [100]:
# Reemplazamos lo "no se midio" por NaN
df['calidad_de_agua'] = df['calidad_de_agua'].replace("no se midió", pd.NA)
#df['calidad_de_agua'].value_counts()

In [101]:
# Aca identificamos las la dif entre como estan escritos
#for idx in df['color'].value_counts().items():
#    print(idx)

In [102]:
# Remplazo los valores q estan escritos distintos para q esten iguales
df['color'] = df['color'].replace("Ausencia ", 'Ausencia')
df['color'] = df['color'].replace("ausenca", 'Ausencia')
df['color'] = df['color'].replace("no se midió", pd.NA)
df['color'] = df['color'].map({'Presencia': True, 'Ausencia': False})

In [103]:
# Aca identificamos las la dif entre como estan escritos
#for idx in df['mat_susp'].value_counts().items():
#    print(idx)

In [104]:
# Remplazo los valores q estan escritos distintos para q esten iguales
df['mat_susp'] = df['mat_susp'].replace("Ausencia ", 'Ausencia')
df['mat_susp'] = df['mat_susp'].replace("no se midió", pd.NA)

#Los pasamos a Booleano para mejor manupilacion 
df['mat_susp'] = df['mat_susp'].map({'Presencia': True, 'Ausencia': False})

In [105]:
# Miramos como quedaron los datos en el dataframe

# df.value_counts(dropna=False)

In [106]:
# Meto en "filas_parcialmente_nan" todas filas que estan en Nulo (excepto las 6 primeras columnas)
# df.isna() me dice que valores son nulos
# sum(axis = 1) suma los nulos pero suma de columna a columna (osea cuantos nulos tiene una fila)
# len(df.columns) - 6  simplemente te dice la longitud (de las columnas) y le resto 6 porq no quiero que tome en cuenta los 6 primeros

filas_parcialmente_nan = df[df.isna().sum(axis=1) == (len(df.columns) - 6)]

In [107]:
# Mostrar las filas con todo NaN
#filas_parcialmente_nan

In [108]:
# Eliminar estas filas
df = df.drop(filas_parcialmente_nan.index)

In [109]:
# Eliminamos las columnas de los datos inncesario

df = df.drop('año', axis=1)
df = df.drop('orden', axis=1)
df = df.drop('fecha', axis=1)

In [110]:
# Eliminar los símbolos < y > de la columna 'valores'

df['colif_fecales_ufc_100ml'] = df['colif_fecales_ufc_100ml'].str.replace('<', '').str.replace('>', '')
df['nitrato_mg_l'] = df['nitrato_mg_l'].str.replace('<', '').str.replace('>', '')
df['nh4_mg_l'] = df['nh4_mg_l'].str.replace('<', '').str.replace('>', '')
df['p_total_l_mg_l'] = df['p_total_l_mg_l'].str.replace('<', '').str.replace('>', '')
df['fosf_ortofos_mg_l'] = df['fosf_ortofos_mg_l'].str.replace('<', '').str.replace('>', '')
df['dbo_mg_l'] = df['dbo_mg_l'].str.replace('<', '').str.replace('>', '')
df['dqo_mg_l'] = df['dqo_mg_l'].str.replace('<', '').str.replace('>', '')
df['turbiedad_ntu'] = df['turbiedad_ntu'].str.replace('<', '').str.replace('>', '')
df['hidr_deriv_petr_ug_l'] = df['hidr_deriv_petr_ug_l'].str.replace('<', '').str.replace('>', '')
df['cr_total_mg_l'] = df['cr_total_mg_l'].str.replace('<', '').str.replace('>', '')
df['cd_total_mg_l'] = df['cd_total_mg_l'].str.replace('<', '').str.replace('>', '')
df['clorofila_a_ug_l'] = df['clorofila_a_ug_l'].str.replace('<', '').str.replace('>', '')
df['microcistina_ug_l'] = df['microcistina_ug_l'].str.replace('<', '').str.replace('>', '')
df['dqo_mg_l'] = df['dqo_mg_l'].str.replace('<', '').str.replace('>', '')
df['dqo_mg_l'] = df['dqo_mg_l'].str.replace('<', '').str.replace('>', '')

In [111]:
# Y ahora que los valores dejaron de ser string , vuelvo a intentar convertirlos en tipo numerico 

df['od'] = pd.to_numeric(df['od'], errors='ignore')
df['ph'] = pd.to_numeric(df['ph'], errors='ignore')
df['colif_fecales_ufc_100ml'] = pd.to_numeric(df['colif_fecales_ufc_100ml'], errors='ignore')
df['escher_coli_ufc_100ml'] = pd.to_numeric(df['escher_coli_ufc_100ml'], errors='ignore')
df['enteroc_ufc_100ml'] = pd.to_numeric(df['enteroc_ufc_100ml'], errors='ignore')
df['nitrato_mg_l'] = pd.to_numeric(df['nitrato_mg_l'], errors='ignore')
df['nh4_mg_l'] = pd.to_numeric(df['nh4_mg_l'], errors='ignore')
df['p_total_l_mg_l'] = pd.to_numeric(df['p_total_l_mg_l'], errors='ignore')
df['fosf_ortofos_mg_l'] = pd.to_numeric(df['fosf_ortofos_mg_l'], errors='ignore')
df['dbo_mg_l'] = pd.to_numeric(df['dbo_mg_l'], errors='ignore')
df['dqo_mg_l'] = pd.to_numeric(df['dqo_mg_l'], errors='ignore')
df['turbiedad_ntu'] = pd.to_numeric(df['turbiedad_ntu'], errors='ignore')
df['hidr_deriv_petr_ug_l'] = pd.to_numeric(df['hidr_deriv_petr_ug_l'], errors='ignore')
df['cr_total_mg_l'] = pd.to_numeric(df['cr_total_mg_l'], errors='ignore')
df['cd_total_mg_l'] = pd.to_numeric(df['cd_total_mg_l'], errors='ignore')
df['clorofila_a_ug_l'] = pd.to_numeric(df['clorofila_a_ug_l'], errors='ignore')
df['microcistina_ug_l'] = pd.to_numeric(df['microcistina_ug_l'], errors='ignore')
df['ica'] = pd.to_numeric(df['ica'], errors='ignore')

C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:3: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['od'] = pd.to_numeric(df['od'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['ph'] = pd.to_numeric(df['ph'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['colif_fecales_ufc_100ml'] = pd.to_numeric(df['colif_fecales_ufc_100ml'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['escher_coli_ufc_100ml'] = pd.to_numeric(df['escher_coli_ufc_100ml'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:7: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['enteroc_ufc_100ml'] = pd.to_numeric(df['enteroc_ufc_100ml'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:8: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['nitrato_mg_l'] = pd.to_numeric(df['nitrato_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:9: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['nh4_mg_l'] = pd.to_numeric(df['nh4_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:10: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['p_total_l_mg_l'] = pd.to_numeric(df['p_total_l_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:11: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['fosf_ortofos_mg_l'] = pd.to_numeric(df['fosf_ortofos_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['dbo_mg_l'] = pd.to_numeric(df['dbo_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:13: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['dqo_mg_l'] = pd.to_numeric(df['dqo_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:14: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['turbiedad_ntu'] = pd.to_numeric(df['turbiedad_ntu'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:15: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['hidr_deriv_petr_ug_l'] = pd.to_numeric(df['hidr_deriv_petr_ug_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:16: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['cr_total_mg_l'] = pd.to_numeric(df['cr_total_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:17: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['cd_total_mg_l'] = pd.to_numeric(df['cd_total_mg_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:18: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['clorofila_a_ug_l'] = pd.to_numeric(df['clorofila_a_ug_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:19: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['microcistina_ug_l'] = pd.to_numeric(df['microcistina_ug_l'], errors='ignore')
C:\Users\berni\AppData\Local\Temp\ipykernel_21688\3530368319.py:20: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df['ica'] = pd.to_numeric(df['ica'], errors='ignore')

In [112]:
# Vuelvo a identificar los tipos
#df.info()

In [113]:
# Miramos que van quedando los datos en la tabla
#df.value_counts(dropna=False)

In [114]:
#Buscamos filas con al menos un NaN
filas_parcialmente_nan = df[df.isna().sum(axis=1) >= 1]

In [115]:
# Miramos los datos que nos arrojo

#filas_parcialmente_nan

In [116]:
# Limpiamos y modificamos nuestros datos
import numpy as np

# Sacamos los P de los ids
df_distancias["ID"] = df_distancias["ID"].str.replace('P', '')
df_distancias["Cerca 1"] = df_distancias["Cerca 1"].str.replace('P', '')
df_distancias["Cerca 2"] = df_distancias["Cerca 2"].str.replace('P', '')


# A las distancias se eliminan los km y los visibilizamos en el nombre de la columna
df_distancias.rename(columns={"Dist 1": "Dist 1 (KM)", "Dist 2": "Dist 2 (KM)"}, inplace= True)
df_distancias["Dist 1 (KM)"] = df_distancias["Dist 1 (KM)"].str.replace("km", "")
df_distancias["Dist 2 (KM)"] = df_distancias["Dist 2 (KM)"].str.replace("km", "")

# Ponemos NaN en los valores correspondientes´
df_distancias["Cerca 2"] = df_distancias["Cerca 2"].replace("-", np.nan)
df_distancias["Dist 2 (KM)"] = df_distancias["Dist 2 (KM)"].replace("-", np.nan)

# Ponemos sus respectivos tipos   
df_distancias["Dist 1 (KM)"] = df_distancias["Dist 1 (KM)"].astype(float)
df_distancias["Dist 2 (KM)"] = df_distancias["Dist 2 (KM)"].astype(float)
df_distancias['ID'] = df_distancias['ID'].astype(str)
df_distancias['Cerca 1'] = df_distancias['Cerca 1'].astype(str)
df_distancias['Cerca 2'] = df_distancias['Cerca 2'].astype(str)

# Vinculamos los Ids de dataframe original con los Ids de nuestro dataframe 
df_identificadores = df[["sitios", "codigo"]].drop_duplicates(subset=["sitios", "codigo"])
df_identificadores.rename(columns={"sitios": "Nombre"}, inplace= True)

#normalicemos los nombres
df_con_id['Nombre'] = df_con_id['Nombre'].str.strip().str.lower()
df_identificadores['Nombre'] = df_identificadores['Nombre'].str.strip().str.lower()

df_aux = pd.merge(df_con_id, df_identificadores, on = "Nombre", how="inner")

#Reemplazamos los ids numericos por los de codigo de texto
id_mapping = dict(zip(df_aux['ID'].astype(str), df_aux['codigo'])) 
#El zip es para que se vuelva clave-valor sin iterar que iterar

#lo paso a float para que coincida despues con el id de distancias 
#reemplazo
for i, fila in df_distancias.iterrows():
    df_distancias.at[i, 'ID'] = id_mapping.get(fila['ID'])
    df_distancias.at[i, 'Cerca 1'] = id_mapping.get(fila['Cerca 1'])
    if df_distancias.at[i, 'Cerca 2'] != np.nan:
        df_distancias.at[i, 'Cerca 2'] = id_mapping.get(fila['Cerca 2'])
    
# Ahora utilizaremos esta información para reemplazar los valores nulos en
# las columnas. Lo haremos de la siguiente manera:
#    + Por cada atributo nulo de una fila buscaremos en df_distancias 
#      los dos puntos más cercanos.
#    
#    + Uno de los puntos (Cerca 1) está situado a la izquierda del punto
#      con el valor nulo, desde este punto corre la corriente, por lo que
#      le damos más importancia que al punto (Cerca 2), el cual está del otro
#      lado del punto. 
#  
#    + Considerando esto le daremos un 80% de importancia a Cerca 1 y un 20% 
#      a Cerca 2

Calcularemos el inverso de las distancias para ver cuanto aporta cada una

Formula 1:
$$ A = X*0.7*\frac{1}{d_1}\ + Y*0.3*\frac{1}{d_2}\ $$

+ Además debemos tener en cuenta la distancia, por lo que haremos lo siguiente:
    + Sumaremos las distancias de Cerca 1 y 2 y veremos cuanto incide cada una diviendo sus distancias respectivas sobre el total

Formula 2:
$$ A = X * 0.7 * \frac{d_1}{d_t}\ + Y * 0.3 * \frac{d_2}{d_t}\ $$

Donde **A** es el atributo a calcular; **X** es el mismo atributo del punto Cerca 1 e **Y** el mismo atributo del punto Cerca 2; **d_t** es la distancia total; **d_1** es la distancia a la que se encuentra el punto Cerca 1 y **d_2** a la que se encuentra el punto Cerca 2

----------------------------------
Veamos las filas de los sitios que les faltan valores

In [117]:
#df.isna().stack() --> para ver como se ve

posiciones_con_nan = df.isna().stack()

posiciones_con_nan = posiciones_con_nan[posiciones_con_nan] # -> se queda con los true

posiciones_con_nan = posiciones_con_nan.reset_index()

posiciones_con_nan.columns = ['Fila', 'Columna', 'EsNan']

print(posiciones_con_nan)

    Fila                  Columna  EsNan
0      4  colif_fecales_ufc_100ml   True
1      4    escher_coli_ufc_100ml   True
2      4        enteroc_ufc_100ml   True
3     20                 dbo_mg_l   True
4     29  colif_fecales_ufc_100ml   True
5     29    escher_coli_ufc_100ml   True
6     29        enteroc_ufc_100ml   True
7     34  colif_fecales_ufc_100ml   True
8     34    escher_coli_ufc_100ml   True
9     34        enteroc_ufc_100ml   True
10    68             nitrato_mg_l   True
11    68        fosf_ortofos_mg_l   True
12    70                 tem_aire   True
13    71                 tem_aire   True
14    72             nitrato_mg_l   True
15    72        fosf_ortofos_mg_l   True
16    74                 tem_aire   True
17    75                 tem_aire   True
18    76             nitrato_mg_l   True
19    76        fosf_ortofos_mg_l   True
20    78                 tem_aire   True
21    79                 tem_aire   True
22    80                 tem_aire   True
23    80             nitrato_mg_l   True
24    80        fosf_ortofos_mg_l   True
25    82                 tem_aire   True
26    83                 tem_aire   True
27    84                 tem_aire   True
28    85            cr_total_mg_l   True
29    88                 tem_aire   True
30    92                 tem_aire   True
31    96                 tem_aire   True
32   100                 tem_aire   True
33   100     hidr_deriv_petr_ug_l   True
34   100        microcistina_ug_l   True
35   104                 dbo_mg_l   True
36   108                 dbo_mg_l   True
37   116                 tem_agua   True
38   116                 dbo_mg_l   True
39   119                 dbo_mg_l   True
40   120                 dbo_mg_l   True
41   123                 dbo_mg_l   True
42   127                 dqo_mg_l   True
43   128                 tem_agua   True
44   128                       od   True
45   128                       ph   True

In [118]:
for i, row in posiciones_con_nan.iterrows():
    fila = row['Fila']
    columna = row['Columna']
    
    # Obtener el código del lugar con NaN
    codigo_lugar = df.at[fila, 'codigo']
    estacion = df.at[fila, 'campaña']
    
    # Buscar los lugares cercanos
    cercanos = df_distancias[df_distancias['ID'] == codigo_lugar][['Cerca 1', 'Cerca 2']].values[0]

    # Buscar los valores de los lugares cercanos en la misma columna
    lista_cerca_1 = df[(df['codigo'] == cercanos[0]) & (df['campaña'] == estacion)][columna].values
    if cercanos[1] != None: #por si no existe el punto cerca 2
        lista_cerca_2 = df[(df['codigo'] == cercanos[1]) & (df['campaña'] == estacion)][columna].values
    else:
        lista_cerca_2 = []

    # Si el valor en esa estación o lugar no existe le asignamos un 0 para que no tenga peso en la formula
    if len(lista_cerca_1) > 0 and not pd.isna(lista_cerca_1[0]):
        valor_cerca_1 = float(lista_cerca_1[0])
    else:
        valor_cerca_1 = np.nan

    if len(lista_cerca_2) > 0 and not pd.isna(lista_cerca_2[0]):
        valor_cerca_2 = float(lista_cerca_2[0])
    else:
        valor_cerca_2 = np.nan

    
    print(valor_cerca_1, pd.isna(valor_cerca_1))
    print(valor_cerca_2, pd.isna(valor_cerca_2))

    # Ahora nos traemos las distancias
    distancias = df_distancias[df_distancias['ID'] == codigo_lugar][['Dist 1 (KM)', 'Dist 2 (KM)']].values[0]
    
    distancia_1 = distancias[0] #la primer distancia está siempre, esto lo sabemos por la tabla
    if not pd.isna(distancias[1]): #como puede faltar la segunda distancia chequeamos que no sea nan
        distancia_2 = distancias[1]
    else:
        distancia_2 = 0 #como no existe el valor en el punto dos no importa el numero que pongamos en distancia
    
    #probemos la primer formula
    if pd.isna(valor_cerca_1) and pd.isna(valor_cerca_2): #si ambos vecinos tienen nan dejamos nan como valor aproximado
        valor_aproximado = np.nan
    else: #si hay algun nan lo cambiamos a 0 para que no tenga peso en la formula
        if pd.isna(valor_cerca_1):
            valor_cerca_1 = 0
        if pd.isna(valor_cerca_2):
            valor_cerca_2 = 0
        #segunda formula
        distancia_total = distancia_1 + distancia_2
        valor_aproximado2 = valor_cerca_1 * 0.7 * (distancia_1 / distancia_total) + valor_cerca_2 * 0.3 * (distancia_2 / distancia_total)
        #primera formula
        if(distancia_2 == 0): #le cambiamos el valor para que no salte error en la division
            distancia_2 = 1 
        valor_aproximado1 = valor_cerca_1 * 0.7 * (1/distancia_1) + valor_cerca_2 * 0.3 * (1/distancia_2)

    # Imprimir la información
    print(f"NaN en fila {fila}, columna {columna}, lugar {codigo_lugar}, estacion {estacion} cercanos: {cercanos}, dist1: {distancia_1}, dist2: {distancia_2}")
    print("Valor aprox1: ", valor_aproximado1, "valor aprox2: ", valor_aproximado2)

    #asignamos el de la formula 1 (por asignar algo por ahora)
    df.at[fila, columna] = valor_aproximado1

4000.0 False
20000.0 False
NaN en fila 4, columna colif_fecales_ufc_100ml, lugar TI006, estacion verano cercanos: ['TI001' 'TI002'], dist1: 5.1, dist2: 1.1
Valor aprox1:  6003.565062388591 valor aprox2:  3367.741935483871
1000.0 False
18000.0 False
NaN en fila 4, columna escher_coli_ufc_100ml, lugar TI006, estacion verano cercanos: ['TI001' 'TI002'], dist1: 5.1, dist2: 1.1
Valor aprox1:  5046.345811051693 valor aprox2:  1533.8709677419356
330.0 False
4600.0 False
NaN en fila 4, columna enteroc_ufc_100ml, lugar TI006, estacion verano cercanos: ['TI001' 'TI002'], dist1: 5.1, dist2: 1.1
Valor aprox1:  1299.8395721925133 valor aprox2:  434.85483870967744
2.3 False
3.7 False
NaN en fila 20, columna dbo_mg_l, lugar TI005, estacion verano cercanos: ['TI004' 'TI007'], dist1: 1.3, dist2: 2.3
Valor aprox1:  1.7210702341137123 valor aprox2:  1.2905555555555557
5300.0 False
nan True
NaN en fila 29, columna colif_fecales_ufc_100ml, lugar TI008, estacion otoño cercanos: ['TI009' None], dist1: 1.3, dist2: 1
Valor aprox1:  2853.8461538461534 valor aprox2:  3709.9999999999995
400.0 False
nan True
NaN en fila 29, columna escher_coli_ufc_100ml, lugar TI008, estacion otoño cercanos: ['TI009' None], dist1: 1.3, dist2: 1
Valor aprox1:  215.38461538461536 valor aprox2:  280.0
90.0 False
nan True
NaN en fila 29, columna enteroc_ufc_100ml, lugar TI008, estacion otoño cercanos: ['TI009' None], dist1: 1.3, dist2: 1
Valor aprox1:  48.46153846153845 valor aprox2:  62.99999999999999
1000.0 False
nan True
NaN en fila 34, columna colif_fecales_ufc_100ml, lugar TI009, estacion invierno cercanos: ['TI008' None], dist1: 1.3, dist2: 1
Valor aprox1:  538.4615384615385 valor aprox2:  700.0
600.0 False
nan True
NaN en fila 34, columna escher_coli_ufc_100ml, lugar TI009, estacion invierno cercanos: ['TI008' None], dist1: 1.3, dist2: 1
Valor aprox1:  323.07692307692304 valor aprox2:  420.0
100.0 False
nan True
NaN en fila 34, columna enteroc_ufc_100ml, lugar TI009, estacion invierno cercanos: ['TI008' None], dist1: 1.3, dist2: 1
Valor aprox1:  53.84615384615384 valor aprox2:  70.0
7.1 False
nan True
NaN en fila 68, columna nitrato_mg_l, lugar CA041, estacion verano cercanos: ['VL031' 'CA044'], dist1: 1.0, dist2: 3.0
Valor aprox1:  4.97 valor aprox2:  1.2425
0.43 False
nan True
NaN en fila 68, columna fosf_ortofos_mg_l, lugar CA041, estacion verano cercanos: ['VL031' 'CA044'], dist1: 1.0, dist2: 3.0
Valor aprox1:  0.301 valor aprox2:  0.07525
11.0 False
nan True
NaN en fila 70, columna tem_aire, lugar CA041, estacion invierno cercanos: ['VL031' 'CA044'], dist1: 1.0, dist2: 3.0
Valor aprox1:  7.699999999999999 valor aprox2:  1.9249999999999998
24.2 False
nan True
NaN en fila 71, columna tem_aire, lugar CA041, estacion primavera cercanos: ['VL031' 'CA044'], dist1: 1.0, dist2: 3.0
Valor aprox1:  16.939999999999998 valor aprox2:  4.234999999999999
4.97 False
nan True
NaN en fila 72, columna nitrato_mg_l, lugar CA044, estacion verano cercanos: ['CA041' 'CA046'], dist1: 3.2, dist2: 3.0
Valor aprox1:  1.0871875 valor aprox2:  1.7956129032258061
0.301 False
nan True
NaN en fila 72, columna fosf_ortofos_mg_l, lugar CA044, estacion verano cercanos: ['CA041' 'CA046'], dist1: 3.2, dist2: 3.0
Valor aprox1:  0.06584374999999999 valor aprox2:  0.10874838709677417
7.699999999999999 False
nan True
NaN en fila 74, columna tem_aire, lugar CA044, estacion invierno cercanos: ['CA041' 'CA046'], dist1: 3.2, dist2: 3.0
Valor aprox1:  1.6843749999999997 valor aprox2:  2.781935483870967
16.939999999999998 False
nan True
NaN en fila 75, columna tem_aire, lugar CA044, estacion primavera cercanos: ['CA041' 'CA046'], dist1: 3.2, dist2: 3.0
Valor aprox1:  3.705624999999999 valor aprox2:  6.120258064516127
1.0871875 False
nan True
NaN en fila 76, columna nitrato_mg_l, lugar CA046, estacion verano cercanos: ['CA044' 'CA047'], dist1: 3.0, dist2: 8.7
Valor aprox1:  0.2536770833333333 valor aprox2:  0.19513621794871797
0.06584374999999999 False
nan True
NaN en fila 76, columna fosf_ortofos_mg_l, lugar CA046, estacion verano cercanos: ['CA044' 'CA047'], dist1: 3.0, dist2: 8.7
Valor aprox1:  0.015363541666666663 valor aprox2:  0.011818108974358973
1.6843749999999997 False
nan True
NaN en fila 78, columna tem_aire, lugar CA046, estacion invierno cercanos: ['CA044' 'CA047'], dist1: 3.0, dist2: 8.7
Valor aprox1:  0.3930208333333332 valor aprox2:  0.30232371794871793
3.705624999999999 False
nan True
NaN en fila 79, columna tem_aire, lugar CA046, estacion primavera cercanos: ['CA044' 'CA047'], dist1: 3.0, dist2: 8.7
Valor aprox1:  0.864645833333333 valor aprox2:  0.6651121794871794
27.0 False
nan True
NaN en fila 80, columna tem_aire, lugar CA047, estacion verano cercanos: ['CA046' 'AV054'], dist1: 9.0, dist2: 2.3
Valor aprox1:  2.0999999999999996 valor aprox2:  15.053097345132741
0.2536770833333333 False
5.2 False
NaN en fila 80, columna nitrato_mg_l, lugar CA047, estacion verano cercanos: ['CA046' 'AV054'], dist1: 9.0, dist2: 2.3
Valor aprox1:  0.6979913093800323 valor aprox2:  0.4589527101769911
0.015363541666666663 False
2.4 False
NaN en fila 80, columna fosf_ortofos_mg_l, lugar CA047, estacion verano cercanos: ['CA046' 'AV054'], dist1: 9.0, dist2: 2.3
Valor aprox1:  0.3142384203904992 valor aprox2:  0.15511418694690263
0.3930208333333332 False
12.6 False
NaN en fila 82, columna tem_aire, lugar CA047, estacion invierno cercanos: ['CA046' 'AV054'], dist1: 9.0, dist2: 2.3
Valor aprox1:  1.6740465479066022 valor aprox2:  0.9884983407079644
0.864645833333333 False
28.0 False
NaN en fila 83, columna tem_aire, lugar CA047, estacion primavera cercanos: ['CA046' 'AV054'], dist1: 9.0, dist2: 2.3
Valor aprox1:  3.7194241445249605 valor aprox2:  2.191793694690265
2.0999999999999996 False
nan True
NaN en fila 84, columna tem_aire, lugar AV054, estacion verano cercanos: ['CA047' 'AV051'], dist1: 2.3, dist2: 1.5
Valor aprox1:  0.6391304347826087 valor aprox2:  0.889736842105263
nan True
100.0 False
NaN en fila 85, columna cr_total_mg_l, lugar AV054, estacion otoño cercanos: ['CA047' 'AV051'], dist1: 2.3, dist2: 1.5
Valor aprox1:  20.0 valor aprox2:  11.842105263157896
0.6391304347826087 False
nan True
NaN en fila 88, columna tem_aire, lugar AV051, estacion verano cercanos: ['AV054' 'AV055'], dist1: 1.5, dist2: 1.5
Valor aprox1:  0.29826086956521736 valor aprox2:  0.22369565217391302
26.0 False
28.0 False
NaN en fila 92, columna tem_aire, lugar AV052, estacion verano cercanos: ['SF015' 'SI022'], dist1: 3.0, dist2: 2.0
Valor aprox1:  10.266666666666666 valor aprox2:  14.280000000000001
0.29826086956521736 False
nan True
NaN en fila 96, columna tem_aire, lugar AV055, estacion verano cercanos: ['AV051' 'AV053'], dist1: 1.5, dist2: 1.8
Valor aprox1:  0.1391884057971014 valor aprox2:  0.09490118577075098
0.1391884057971014 False
18.0 False
NaN en fila 100, columna tem_aire, lugar AV053, estacion verano cercanos: ['AV055' 'QU061'], dist1: 1.8, dist2: 5.1
Valor aprox1:  1.1129523538884152 valor aprox2:  4.0167213610586
100.0 False
100.0 False
NaN en fila 100, columna hidr_deriv_petr_ug_l, lugar AV053, estacion verano cercanos: ['AV055' 'QU061'], dist1: 1.8, dist2: 5.1
Valor aprox1:  44.771241830065364 valor aprox2:  40.434782608695656
0.15 False
0.15 False
NaN en fila 100, columna microcistina_ug_l, lugar AV053, estacion verano cercanos: ['AV055' 'QU061'], dist1: 1.8, dist2: 5.1
Valor aprox1:  0.06715686274509804 valor aprox2:  0.06065217391304348
9.1 False
nan True
NaN en fila 104, columna dbo_mg_l, lugar QU061, estacion verano cercanos: ['AV053' 'QU062'], dist1: 5.0, dist2: 2.5
Valor aprox1:  1.274 valor aprox2:  4.246666666666666
1.274 False
4.0 False
NaN en fila 108, columna dbo_mg_l, lugar QU062, estacion verano cercanos: ['QU061' 'QU063'], dist1: 2.5, dist2: 1.3
Valor aprox1:  1.2797969230769228 valor aprox2:  0.9972368421052631
25.5 False
25.5 False
NaN en fila 116, columna tem_agua, lugar BZ078, estacion verano cercanos: ['QU063' 'BZ077'], dist1: 5.5, dist2: 4.18
Valor aprox1:  5.075598086124401 valor aprox2:  13.445454545454545
4.0 False
nan True
NaN en fila 116, columna dbo_mg_l, lugar BZ078, estacion verano cercanos: ['QU063' 'BZ077'], dist1: 5.5, dist2: 4.18
Valor aprox1:  0.509090909090909 valor aprox2:  1.590909090909091
4.4 False
nan True
NaN en fila 119, columna dbo_mg_l, lugar BZ078, estacion primavera cercanos: ['QU063' 'BZ077'], dist1: 5.5, dist2: 4.18
Valor aprox1:  0.56 valor aprox2:  1.7500000000000002
0.509090909090909 False
6.0 False
NaN en fila 120, columna dbo_mg_l, lugar BZ077, estacion verano cercanos: ['BZ078' 'BZ080'], dist1: 4.0, dist2: 2.4
Valor aprox1:  0.8390909090909091 valor aprox2:  0.8977272727272725
0.56 False
13.0 False
NaN en fila 123, columna dbo_mg_l, lugar BZ077, estacion primavera cercanos: ['BZ078' 'BZ080'], dist1: 4.0, dist2: 2.4
Valor aprox1:  1.723 valor aprox2:  1.7074999999999996
52.0 False
61.0 False
NaN en fila 127, columna dqo_mg_l, lugar BZ080, estacion primavera cercanos: ['BZ077' 'EN-adic'], dist1: 2.3, dist2: 8.8
Valor aprox1:  17.905632411067195 valor aprox2:  22.050450450450448
26.0 False
22.7 False
NaN en fila 128, columna tem_agua, lugar EN-adic, estacion primavera cercanos: ['BZ080' 'EN081'], dist1: 8.8, dist2: 6.8
Valor aprox1:  3.069652406417112 valor aprox2:  13.235128205128204
11.52 False
12.22 False
NaN en fila 128, columna od, lugar EN-adic, estacion primavera cercanos: ['BZ080' 'EN081'], dist1: 8.8, dist2: 6.8
Valor aprox1:  1.45548128342246 valor aprox2:  6.146923076923077
8.94 False
9.18 False
NaN en fila 128, columna ph, lugar EN-adic, estacion primavera cercanos: ['BZ080' 'EN081'], dist1: 8.8, dist2: 6.8
Valor aprox1:  1.1161363636363637 valor aprox2:  4.730615384615383

In [119]:
pd.set_option('display.max_columns', None)
df[df['codigo'] == 'TI006']

,sitios,codigo,campaña,tem_agua,tem_aire,od,ph,olores,color,espumas,mat_susp,colif_fecales_ufc_100ml,escher_coli_ufc_100ml,enteroc_ufc_100ml,nitrato_mg_l,nh4_mg_l,p_total_l_mg_l,fosf_ortofos_mg_l,dbo_mg_l,dqo_mg_l,turbiedad_ntu,hidr_deriv_petr_ug_l,cr_total_mg_l,cd_total_mg_l,clorofila_a_ug_l,microcistina_ug_l,ica,calidad_de_agua
4,Río Lujan y Arroyo Caraguatá,TI006,verano,25.7,26.0,4.31,7.4,False,True,False,False,6003.565062,5046.345811,1299.839572,3.9,0.21,1.10,0.27,3.7,30.0,31.0,100.0,5.000,0.001,0.00500,0.15,49.0,Muy deteriorada
5,Río Lujan y Arroyo Caraguatá,TI006,otoño,15.7,13.0,6.90,7.0,False,False,False,False,30000.000000,1000.000000,800.000000,2.9,0.57,0.19,0.20,4.3,2.0,30.0,150.0,100.000,0.005,0.00100,10.00,39.0,Extremadamente deteriorada
6,Río Lujan y Arroyo Caraguatá,TI006,invierno,14.5,13.0,2.54,6.8,False,False,False,False,10000.000000,2000.000000,150.000000,2.0,4.70,0.48,0.57,6.8,30.0,22.0,100.0,0.005,0.001,0.01300,0.20,43.0,Extremadamente deteriorada
7,Río Lujan y Arroyo Caraguatá,TI006,primavera,25.4,33.0,6.20,6.9,False,False,False,True,2000.000000,1000.000000,58.000000,4.2,3.30,0.20,0.14,2.0,37.0,36.0,100.0,0.005,0.001,0.00415,0.20,48.0,Muy deteriorada

In [120]:
df[df['codigo'].str.startswith('BZ')].sort_values(by='campaña')

,sitios,codigo,campaña,tem_agua,tem_aire,od,ph,olores,color,espumas,mat_susp,colif_fecales_ufc_100ml,escher_coli_ufc_100ml,enteroc_ufc_100ml,nitrato_mg_l,nh4_mg_l,p_total_l_mg_l,fosf_ortofos_mg_l,dbo_mg_l,dqo_mg_l,turbiedad_ntu,hidr_deriv_petr_ug_l,cr_total_mg_l,cd_total_mg_l,clorofila_a_ug_l,microcistina_ug_l,ica,calidad_de_agua
118,Calle 14 y Costa - Salida cloaca,BZ078,invierno,12.000000,16.0,10.13,8.63,False,False,False,False,10000.0,500.0,100.0,4.1,0.60,0.29,0.24,7.100000,64.000000,16.0,100.0,0.0050,0.001,0.01000,0.20,45.0,Muy deteriorada
122,Puerto Trinidad calle 47,BZ077,invierno,13.000000,12.5,11.82,8.80,False,False,False,False,1000.0,100.0,300.0,3.5,0.70,0.22,0.20,7.700000,125.000000,12.0,100.0,0.0050,0.001,0.01000,0.20,61.0,Muy deteriorada
126,Costanera Hudson Calle 63,BZ080,invierno,12.000000,10.0,10.16,9.36,False,False,False,False,10000.0,1000.0,100.0,3.4,0.70,0.20,0.15,9.400000,62.000000,21.0,100.0,0.0052,0.001,0.22100,0.20,43.0,Extremadamente deteriorada
117,Calle 14 y Costa - Salida cloaca,BZ078,otoño,13.000000,18.0,15.20,9.66,False,False,False,False,20000.0,1000.0,500.0,4.3,0.08,0.22,0.22,3.000000,9.500000,40.0,65.0,100.0000,0.005,0.00100,10.00,42.0,Extremadamente deteriorada
121,Puerto Trinidad calle 47,BZ077,otoño,13.000000,16.0,12.39,9.23,False,False,False,False,29000.0,1000.0,800.0,5.9,0.24,0.22,0.22,4.200000,9.800000,33.0,75.0,100.0000,0.005,0.00100,10.00,41.0,Extremadamente deteriorada
125,Costanera Hudson Calle 63,BZ080,otoño,11.000000,15.0,12.67,9.44,False,False,False,False,5000.0,800.0,600.0,3.2,0.10,0.75,0.75,3.100000,11.000000,43.0,80.0,100.0000,0.008,0.00100,10.00,44.0,Extremadamente deteriorada
119,Calle 14 y Costa - Salida cloaca,BZ078,primavera,27.000000,27.5,12.65,9.18,False,False,False,False,6000.0,1400.0,100.0,5.7,0.89,0.75,0.59,0.560000,140.000000,70.0,100.0,0.0050,0.001,0.21265,0.20,39.0,Extremadamente deteriorada
123,Puerto Trinidad calle 47,BZ077,primavera,26.000000,26.0,12.47,9.07,False,False,False,False,800.0,200.0,30.0,5.9,0.50,0.36,0.25,1.723000,52.000000,27.0,100.0,0.0050,0.001,0.09909,0.20,52.0,Muy deteriorada
127,Costanera Hudson Calle 63,BZ080,primavera,26.000000,26.0,11.52,8.94,False,False,False,False,190000.0,20000.0,500.0,5.4,0.34,0.47,0.19,13.000000,17.905632,50.0,100.0,0.0057,0.001,0.84016,0.20,33.0,Extremadamente deteriorada
116,Calle 14 y Costa - Salida cloaca,BZ078,verano,5.075598,28.5,12.87,9.31,True,False,False,True,6000.0,5000.0,185.0,4.0,0.42,0.82,0.50,0.509091,59.000000,75.0,100.0,8.6000,0.001,0.05300,0.15,33.0,Extremadamente deteriorada
120,Puerto Trinidad calle 47,BZ077,verano,25.500000,26.0,7.51,7.65,False,False,False,False,3000.0,2800.0,3000.0,6.2,0.54,0.64,0.94,0.839091,55.000000,120.0,100.0,44.0000,0.001,0.01900,0.15,35.0,Extremadamente deteriorada
124,Costanera Hudson Calle 63,BZ080,verano,23.500000,26.0,9.05,7.87,False,False,False,False,2250.0,500.0,185.0,4.1,0.15,0.58,0.59,6.000000,50.000000,50.0,100.0,7.8000,0.001,0.06100,0.15,51.0,Muy deteriorada

In [121]:

df[df['codigo'].isin(df_distancias['ID'])].shape

(69, 28)